module.exports = [
  {
    item_name: "Dog food",
    amount: 100,
    date: "December 12, 2022",
    from: "Pet Store",
    category: "Pets",
    id: 11,
  },
  {
    item_name: "New Office Clothes",
    amount: 300,
    date: "November 15, 2022",
    from: "H&M",
    category: "Clothes",
    id: 12,
  },
  {
    item_name: "Check",
    amount: 8000,
    date: "December 1, 2022",
    from: "Google",
    category: "Income",
    id: 13,
  },
  {
    item_name: "Check",
    amount: 8000,
    date: "November 1, 2022",
    from: "Google",
    category: "Income",
    id: 13,
  },
  {
    item_name: "Monthly Rent",
    amount: 4000,
    date: "November 5, 2022",
    from: "Landlord",
    category: "Rent",
    id: 13,
  },
];
