module.exports = [
  {
    item_name: "Dog food",
    amount: 100,
    date: "2022-12-12",
    from: "Pet Store",
    category: "Pets",
    id: 11,
  },
  {
    item_name: "New Office Clothes",
    amount: 300,
    date: "2022-11-15",
    from: "H&M",
    category: "Clothes",
    id: 12,
  },
  {
    item_name: "Check",
    amount: 8000,
    date: "2022-12-01",
    from: "Google",
    category: "Income",
    id: 13,
  },
  {
    item_name: "Check",
    amount: 8000,
    date: "2022-11-01",
    from: "Google",
    category: "Income",
    id: 14,
  },
  {
    item_name: "Monthly Rent",
    amount: 4000,
    date: "2022-11-05",
    from: "Landlord",
    category: "Rent",
    id: 15,
  },
];
